
.PHONY: do_all iupview iupviewgtk
do_all: iupview

iupview:
	@$(MAKE) --no-print-directory -f ../tecmake_compact.mak 

iupviewgtk:
	@$(MAKE) --no-print-directory -f ../tecmake_compact.mak USE_GTK=Yes
