
.PHONY: do_all cd_freetype cd cd_pdflib cdpdf cdcontextplus cdlua3 cdluapdf3 cdlua5 cdluapdf5 cdluacontextplus5 cdluaim5
#do_all: cd_freetype cd cd_pdflib cdpdf cdcontextplus cdlua3 cdluapdf3 cdlua5 cdluapdf5 cdluacontextplus5 cdluaim5
do_all: cd_freetype cd cd_pdflib cdpdf cdcontextplus cdlua5 cdluapdf5 cdluacontextplus5 cdluaim5

cd_freetype:
	@$(MAKE) --no-print-directory -f tecmake_compact.mak MF=cd_freetype
cd:
	@$(MAKE) --no-print-directory -f tecmake_compact.mak 
cd_pdflib:
	@$(MAKE) --no-print-directory -f tecmake_compact.mak MF=cd_pdflib
cdpdf:
	@$(MAKE) --no-print-directory -f tecmake_compact.mak MF=cdpdf
cdcontextplus:
	@$(MAKE) --no-print-directory -f tecmake_compact.mak MF=cdcontextplus
cdlua3:
	@$(MAKE) --no-print-directory -f tecmake_compact.mak MF=cdlua3
cdluapdf3:
	@$(MAKE) --no-print-directory -f tecmake_compact.mak MF=cdluapdf3
cdlua5:
	@$(MAKE) --no-print-directory -f tecmake_compact.mak MF=cdlua5
cdluapdf5:
	@$(MAKE) --no-print-directory -f tecmake_compact.mak MF=cdluapdf5
cdluacontextplus5:
	@$(MAKE) --no-print-directory -f tecmake_compact.mak MF=cdluacontextplus5
cdluaim5:
	@$(MAKE) --no-print-directory -f tecmake_compact.mak MF=cdluaim5
